// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstMenuCommand
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFirstCommandPackageString = "9fbaea06-4e45-46c9-b2cd-92f8da459f78";
        public static Guid guidFirstCommandPackage = new Guid(guidFirstCommandPackageString);

        public const string guidFirstCommandPackageCmdSetString = "8b5a50cc-a03c-443b-9d32-167f373f1da6";
        public static Guid guidFirstCommandPackageCmdSet = new Guid(guidFirstCommandPackageCmdSetString);

        public const string guidImagesString = "c1bee08d-90a0-46f9-8dab-e504d0ae14c6";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FirstCommandId = 0x0100;
        public const int InsertReferenceCommandId = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}